---
- name: Wait {{ netlab_initial_delay }} seconds for OS10 to start waking up
  ansible.builtin.pause:
    seconds: "{{ netlab_initial_delay }}"

- name: Wait for SSH server on OS10 to become ready
  ansible.builtin.include_tasks: ssh.yml
