- name: Wait {{ netlab_initial_delay }} seconds for OS10 to start waking up
  pause:
    seconds: "{{ netlab_initial_delay }}"

- name: Wait for SSH server on OS10 to become ready
  include_tasks: ssh.yml
