---
- name: Attempt to load VRF kernel module
  when: netlab_mgmt_vrf|default(False) or 'vrf' in module|default([])
  ansible.builtin.shell: |
    modprobe vrf || echo "FAILED"
  become: true
  delegate_to: localhost
  run_once: true
  tags: [print_action, always]
  register: modprobe_result
  ignore_errors: true

- name: Disable FRR management VRF when modprobe fails
  when: modprobe_result.stdout|default('') is search("FAILED")
  ansible.builtin.set_fact:
    netlab_mgmt_vrf: false

- ansible.builtin.include_tasks: deploy-config.yml
  tags: [print_action, always]
