---
- community.routeros.command:
    commands: /export
  register: ros_exp_config

- ansible.builtin.set_fact:
    ansible_net_config: "{{ ros_exp_config.stdout_lines[0] | reject('match', '^$') | list | join('\n') }}\n"
